// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddMessageMessagesPostData, AddMessageMessagesPostErrors, AddMessageMessagesPostResponses, AttachToolAgentsAgentIdToolsToolIdPostData, AttachToolAgentsAgentIdToolsToolIdPostErrors, AttachToolAgentsAgentIdToolsToolIdPostResponses, CreateAgentAgentsPostData, CreateAgentAgentsPostErrors, CreateAgentAgentsPostResponses, CreateChatChatsPostData, CreateChatChatsPostErrors, CreateChatChatsPostResponses, CreateToolToolsPostData, CreateToolToolsPostErrors, CreateToolToolsPostResponses, DeleteAgentAgentsAgentIdDeleteData, DeleteAgentAgentsAgentIdDeleteErrors, DeleteAgentAgentsAgentIdDeleteResponses, DeleteToolToolsToolIdDeleteData, DeleteToolToolsToolIdDeleteErrors, DeleteToolToolsToolIdDeleteResponses, DetachToolAgentsAgentIdToolsToolIdDeleteData, DetachToolAgentsAgentIdToolsToolIdDeleteErrors, DetachToolAgentsAgentIdToolsToolIdDeleteResponses, GetAgentAgentsAgentIdGetData, GetAgentAgentsAgentIdGetErrors, GetAgentAgentsAgentIdGetResponses, GetChatChatsChatIdGetData, GetChatChatsChatIdGetErrors, GetChatChatsChatIdGetResponses, GetToolToolsToolIdGetData, GetToolToolsToolIdGetErrors, GetToolToolsToolIdGetResponses, ListAgentsAgentsGetData, ListAgentsAgentsGetErrors, ListAgentsAgentsGetResponses, ListAgentToolsAgentsAgentIdToolsGetData, ListAgentToolsAgentsAgentIdToolsGetErrors, ListAgentToolsAgentsAgentIdToolsGetResponses, ListChatsChatsGetData, ListChatsChatsGetErrors, ListChatsChatsGetResponses, ListMessagesMessagesByChatChatIdGetData, ListMessagesMessagesByChatChatIdGetErrors, ListMessagesMessagesByChatChatIdGetResponses, ListToolsToolsGetData, ListToolsToolsGetResponses, UpdateAgentAgentsAgentIdPatchData, UpdateAgentAgentsAgentIdPatchErrors, UpdateAgentAgentsAgentIdPatchResponses, UpdateToolToolsToolIdPatchData, UpdateToolToolsToolIdPatchErrors, UpdateToolToolsToolIdPatchResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List Tools
 */
export const listToolsToolsGet = <ThrowOnError extends boolean = false>(options?: Options<ListToolsToolsGetData, ThrowOnError>) => (options?.client ?? client).get<ListToolsToolsGetResponses, unknown, ThrowOnError>({ url: '/tools', ...options });

/**
 * Create Tool
 */
export const createToolToolsPost = <ThrowOnError extends boolean = false>(options: Options<CreateToolToolsPostData, ThrowOnError>) => (options.client ?? client).post<CreateToolToolsPostResponses, CreateToolToolsPostErrors, ThrowOnError>({
    url: '/tools',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Tool
 */
export const deleteToolToolsToolIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteToolToolsToolIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteToolToolsToolIdDeleteResponses, DeleteToolToolsToolIdDeleteErrors, ThrowOnError>({ url: '/tools/{tool_id}', ...options });

/**
 * Get Tool
 */
export const getToolToolsToolIdGet = <ThrowOnError extends boolean = false>(options: Options<GetToolToolsToolIdGetData, ThrowOnError>) => (options.client ?? client).get<GetToolToolsToolIdGetResponses, GetToolToolsToolIdGetErrors, ThrowOnError>({ url: '/tools/{tool_id}', ...options });

/**
 * Update Tool
 */
export const updateToolToolsToolIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateToolToolsToolIdPatchData, ThrowOnError>) => (options.client ?? client).patch<UpdateToolToolsToolIdPatchResponses, UpdateToolToolsToolIdPatchErrors, ThrowOnError>({
    url: '/tools/{tool_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Agents
 */
export const listAgentsAgentsGet = <ThrowOnError extends boolean = false>(options?: Options<ListAgentsAgentsGetData, ThrowOnError>) => (options?.client ?? client).get<ListAgentsAgentsGetResponses, ListAgentsAgentsGetErrors, ThrowOnError>({ url: '/agents', ...options });

/**
 * Create Agent
 */
export const createAgentAgentsPost = <ThrowOnError extends boolean = false>(options: Options<CreateAgentAgentsPostData, ThrowOnError>) => (options.client ?? client).post<CreateAgentAgentsPostResponses, CreateAgentAgentsPostErrors, ThrowOnError>({
    url: '/agents',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Agent
 */
export const deleteAgentAgentsAgentIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteAgentAgentsAgentIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteAgentAgentsAgentIdDeleteResponses, DeleteAgentAgentsAgentIdDeleteErrors, ThrowOnError>({ url: '/agents/{agent_id}', ...options });

/**
 * Get Agent
 */
export const getAgentAgentsAgentIdGet = <ThrowOnError extends boolean = false>(options: Options<GetAgentAgentsAgentIdGetData, ThrowOnError>) => (options.client ?? client).get<GetAgentAgentsAgentIdGetResponses, GetAgentAgentsAgentIdGetErrors, ThrowOnError>({ url: '/agents/{agent_id}', ...options });

/**
 * Update Agent
 */
export const updateAgentAgentsAgentIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateAgentAgentsAgentIdPatchData, ThrowOnError>) => (options.client ?? client).patch<UpdateAgentAgentsAgentIdPatchResponses, UpdateAgentAgentsAgentIdPatchErrors, ThrowOnError>({
    url: '/agents/{agent_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Agent Tools
 */
export const listAgentToolsAgentsAgentIdToolsGet = <ThrowOnError extends boolean = false>(options: Options<ListAgentToolsAgentsAgentIdToolsGetData, ThrowOnError>) => (options.client ?? client).get<ListAgentToolsAgentsAgentIdToolsGetResponses, ListAgentToolsAgentsAgentIdToolsGetErrors, ThrowOnError>({ url: '/agents/{agent_id}/tools', ...options });

/**
 * Detach Tool
 */
export const detachToolAgentsAgentIdToolsToolIdDelete = <ThrowOnError extends boolean = false>(options: Options<DetachToolAgentsAgentIdToolsToolIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DetachToolAgentsAgentIdToolsToolIdDeleteResponses, DetachToolAgentsAgentIdToolsToolIdDeleteErrors, ThrowOnError>({ url: '/agents/{agent_id}/tools/{tool_id}', ...options });

/**
 * Attach Tool
 */
export const attachToolAgentsAgentIdToolsToolIdPost = <ThrowOnError extends boolean = false>(options: Options<AttachToolAgentsAgentIdToolsToolIdPostData, ThrowOnError>) => (options.client ?? client).post<AttachToolAgentsAgentIdToolsToolIdPostResponses, AttachToolAgentsAgentIdToolsToolIdPostErrors, ThrowOnError>({ url: '/agents/{agent_id}/tools/{tool_id}', ...options });

/**
 * List Chats
 */
export const listChatsChatsGet = <ThrowOnError extends boolean = false>(options?: Options<ListChatsChatsGetData, ThrowOnError>) => (options?.client ?? client).get<ListChatsChatsGetResponses, ListChatsChatsGetErrors, ThrowOnError>({ url: '/chats', ...options });

/**
 * Create Chat
 */
export const createChatChatsPost = <ThrowOnError extends boolean = false>(options: Options<CreateChatChatsPostData, ThrowOnError>) => (options.client ?? client).post<CreateChatChatsPostResponses, CreateChatChatsPostErrors, ThrowOnError>({
    url: '/chats',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Chat
 */
export const getChatChatsChatIdGet = <ThrowOnError extends boolean = false>(options: Options<GetChatChatsChatIdGetData, ThrowOnError>) => (options.client ?? client).get<GetChatChatsChatIdGetResponses, GetChatChatsChatIdGetErrors, ThrowOnError>({ url: '/chats/{chat_id}', ...options });

/**
 * List Messages
 */
export const listMessagesMessagesByChatChatIdGet = <ThrowOnError extends boolean = false>(options: Options<ListMessagesMessagesByChatChatIdGetData, ThrowOnError>) => (options.client ?? client).get<ListMessagesMessagesByChatChatIdGetResponses, ListMessagesMessagesByChatChatIdGetErrors, ThrowOnError>({ url: '/messages/by-chat/{chat_id}', ...options });

/**
 * Add Message
 */
export const addMessageMessagesPost = <ThrowOnError extends boolean = false>(options: Options<AddMessageMessagesPostData, ThrowOnError>) => (options.client ?? client).post<AddMessageMessagesPostResponses, AddMessageMessagesPostErrors, ThrowOnError>({
    url: '/messages',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
