// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Agent
 */
export type Agent = {
    /**
     * Id
     */
    id?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Role
     */
    role: string;
    /**
     * Instructions
     */
    instructions: string | null;
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Model
     */
    model?: {
        [key: string]: unknown;
    };
    /**
     * Context Tool
     */
    context_tool?: {
        [key: string]: unknown;
    } | null;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Updated At
     */
    updated_at?: string;
};

/**
 * AgentContextTool
 */
export type AgentContextTool = {
    /**
     * Tool Id
     */
    tool_id: string;
    mode?: ContextInjectionMode;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    };
};

/**
 * AgentCreate
 */
export type AgentCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Role
     */
    role: string;
    /**
     * Instructions
     */
    instructions?: string | null;
    /**
     * Enabled
     */
    enabled?: boolean;
    model?: AgentModelConfig | null;
    context_tool?: AgentContextTool | null;
};

/**
 * AgentModelConfig
 */
export type AgentModelConfig = {
    /**
     * Provider
     */
    provider?: string;
    /**
     * Model
     */
    model: string;
    /**
     * Temperature
     */
    temperature?: number;
    /**
     * Max Output Tokens
     */
    max_output_tokens?: number | null;
    /**
     * Params
     */
    params?: {
        [key: string]: unknown;
    };
};

/**
 * AgentUpdate
 */
export type AgentUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Role
     */
    role?: string | null;
    /**
     * Instructions
     */
    instructions: string | null;
    /**
     * Enabled
     */
    enabled?: boolean | null;
    model?: AgentModelConfig | null;
    context_tool?: AgentContextTool | null;
};

/**
 * Chat
 */
export type Chat = {
    /**
     * Id
     */
    id?: string;
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Updated At
     */
    updated_at?: string;
};

/**
 * ChatCreate
 */
export type ChatCreate = {
    /**
     * Agent Id
     */
    agent_id: string;
};

/**
 * ContextInjectionMode
 */
export type ContextInjectionMode = 'system' | 'user' | 'tool';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HttpBinding
 *
 * Optional: explicit mapping of inputs -> HTTP request parts.
 * If omitted, your dispatcher can default: GET->query, others->json.
 */
export type HttpBinding = {
    /**
     * Query
     */
    query?: Array<string>;
    /**
     * Json
     */
    json?: Array<string>;
    /**
     * Form
     */
    form?: Array<string>;
    /**
     * Path
     */
    path?: Array<string>;
};

/**
 * JsonSchemaProperty
 */
export type JsonSchemaProperty = {
    /**
     * Type
     */
    type?: 'string' | 'integer' | 'number' | 'boolean' | 'object' | 'array' | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Enum
     */
    enum?: Array<unknown> | null;
    /**
     * Default
     */
    default?: unknown | null;
    /**
     * Minlength
     */
    minLength?: number | null;
    /**
     * Maxlength
     */
    maxLength?: number | null;
    /**
     * Minimum
     */
    minimum?: number | null;
    /**
     * Maximum
     */
    maximum?: number | null;
    /**
     * Properties
     */
    properties?: {
        [key: string]: JsonSchemaProperty;
    } | null;
    items?: JsonSchemaProperty | null;
};

/**
 * Message
 */
export type Message = {
    /**
     * Id
     */
    id?: string;
    /**
     * Chat Id
     */
    chat_id: string;
    role: MessageRole;
    /**
     * Content
     */
    content?: string;
    /**
     * Tool Call
     */
    tool_call?: {
        [key: string]: unknown;
    } | null;
    /**
     * Tool Result
     */
    tool_result?: {
        [key: string]: unknown;
    } | null;
    /**
     * Created At
     */
    created_at?: string;
};

/**
 * MessageCreate
 */
export type MessageCreate = {
    /**
     * Chat Id
     */
    chat_id: string;
    role: MessageRole;
    /**
     * Content
     */
    content?: string;
    tool_call?: ToolCallPayload | null;
    tool_result?: ToolResultPayload | null;
};

/**
 * MessageRole
 */
export type MessageRole = 'system' | 'user' | 'assistant' | 'tool_call' | 'tool_result';

/**
 * Tool
 */
export type Tool = {
    /**
     * Id
     */
    id?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Endpoint
     */
    endpoint?: {
        [key: string]: unknown;
    };
    /**
     * Contract
     */
    contract?: {
        [key: string]: unknown;
    };
    /**
     * Response
     */
    response?: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Updated At
     */
    updated_at?: string;
};

/**
 * ToolCallPayload
 */
export type ToolCallPayload = {
    /**
     * Tool Name
     */
    tool_name: string;
    /**
     * Arguments
     */
    arguments?: {
        [key: string]: unknown;
    };
    /**
     * Call Id
     */
    call_id?: string | null;
};

/**
 * ToolContract
 */
export type ToolContract = {
    /**
     * Schema Version
     */
    schema_version?: 'jsonschema-2020-12' | 'jsonschema-draft-07';
    input_schema: ToolInputSchema;
    http?: HttpBinding | null;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Examples
     */
    examples?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Read Only
     */
    read_only?: boolean;
    /**
     * Idempotent
     */
    idempotent?: boolean;
    /**
     * Cache Ttl Seconds
     */
    cache_ttl_seconds?: number | null;
};

/**
 * ToolCreate
 *
 * Incoming payload for creating a tool.
 *
 * NOTE:
 * - endpoint/contract/response are validated as *structured* models,
 * then stored as dicts in Tool.endpoint/Tool.contract/Tool.response.
 */
export type ToolCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Enabled
     */
    enabled?: boolean;
    endpoint?: ToolEndpoint | null;
    contract?: ToolContract | null;
    response?: ToolResponseSpec | null;
};

/**
 * ToolEndpoint
 */
export type ToolEndpoint = {
    transport: ToolTransport;
    /**
     * Url
     */
    url?: string | null;
    /**
     * Method
     */
    method?: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS' | null;
    /**
     * Headers
     */
    headers?: {
        [key: string]: string;
    };
    /**
     * Mcp Server
     */
    mcp_server?: string | null;
    /**
     * Mcp Tool
     */
    mcp_tool?: string | null;
    /**
     * Target
     */
    target?: string | null;
};

/**
 * ToolInputSchema
 */
export type ToolInputSchema = {
    /**
     * Type
     */
    type?: 'object';
    /**
     * Properties
     */
    properties?: {
        [key: string]: JsonSchemaProperty;
    };
    /**
     * Required
     */
    required?: Array<string>;
    /**
     * Additionalproperties
     */
    additionalProperties?: boolean;
};

/**
 * ToolResponseSpec
 */
export type ToolResponseSpec = {
    /**
     * Schema
     */
    schema?: {
        [key: string]: unknown;
    };
    /**
     * Format
     */
    format?: string;
};

/**
 * ToolResultPayload
 */
export type ToolResultPayload = {
    /**
     * Tool Name
     */
    tool_name: string;
    /**
     * Result
     */
    result?: unknown;
    /**
     * Call Id
     */
    call_id?: string | null;
    /**
     * Is Error
     */
    is_error?: boolean;
    /**
     * Error Message
     */
    error_message?: string | null;
};

/**
 * ToolTransport
 */
export type ToolTransport = 'http' | 'mcp' | 'internal';

/**
 * ToolUpdate
 *
 * Partial update payload. Any field can be omitted.
 */
export type ToolUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Enabled
     */
    enabled?: boolean | null;
    endpoint?: ToolEndpoint | null;
    contract?: ToolContract | null;
    response?: ToolResponseSpec | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ListToolsToolsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tools';
};

export type ListToolsToolsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateToolToolsPostData = {
    body: ToolCreate;
    path?: never;
    query?: never;
    url: '/tools';
};

export type CreateToolToolsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateToolToolsPostError = CreateToolToolsPostErrors[keyof CreateToolToolsPostErrors];

export type CreateToolToolsPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type DeleteToolToolsToolIdDeleteData = {
    body?: never;
    path: {
        /**
         * Tool Id
         */
        tool_id: string;
    };
    query?: never;
    url: '/tools/{tool_id}';
};

export type DeleteToolToolsToolIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteToolToolsToolIdDeleteError = DeleteToolToolsToolIdDeleteErrors[keyof DeleteToolToolsToolIdDeleteErrors];

export type DeleteToolToolsToolIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteToolToolsToolIdDeleteResponse = DeleteToolToolsToolIdDeleteResponses[keyof DeleteToolToolsToolIdDeleteResponses];

export type GetToolToolsToolIdGetData = {
    body?: never;
    path: {
        /**
         * Tool Id
         */
        tool_id: string;
    };
    query?: never;
    url: '/tools/{tool_id}';
};

export type GetToolToolsToolIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetToolToolsToolIdGetError = GetToolToolsToolIdGetErrors[keyof GetToolToolsToolIdGetErrors];

export type GetToolToolsToolIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateToolToolsToolIdPatchData = {
    body: ToolUpdate;
    path: {
        /**
         * Tool Id
         */
        tool_id: string;
    };
    query?: never;
    url: '/tools/{tool_id}';
};

export type UpdateToolToolsToolIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateToolToolsToolIdPatchError = UpdateToolToolsToolIdPatchErrors[keyof UpdateToolToolsToolIdPatchErrors];

export type UpdateToolToolsToolIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListAgentsAgentsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Enabled
         */
        enabled?: boolean | null;
    };
    url: '/agents';
};

export type ListAgentsAgentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAgentsAgentsGetError = ListAgentsAgentsGetErrors[keyof ListAgentsAgentsGetErrors];

export type ListAgentsAgentsGetResponses = {
    /**
     * Response List Agents Agents Get
     *
     * Successful Response
     */
    200: Array<Agent>;
};

export type ListAgentsAgentsGetResponse = ListAgentsAgentsGetResponses[keyof ListAgentsAgentsGetResponses];

export type CreateAgentAgentsPostData = {
    body: AgentCreate;
    path?: never;
    query?: never;
    url: '/agents';
};

export type CreateAgentAgentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAgentAgentsPostError = CreateAgentAgentsPostErrors[keyof CreateAgentAgentsPostErrors];

export type CreateAgentAgentsPostResponses = {
    /**
     * Successful Response
     */
    200: Agent;
};

export type CreateAgentAgentsPostResponse = CreateAgentAgentsPostResponses[keyof CreateAgentAgentsPostResponses];

export type DeleteAgentAgentsAgentIdDeleteData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/agents/{agent_id}';
};

export type DeleteAgentAgentsAgentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAgentAgentsAgentIdDeleteError = DeleteAgentAgentsAgentIdDeleteErrors[keyof DeleteAgentAgentsAgentIdDeleteErrors];

export type DeleteAgentAgentsAgentIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAgentAgentsAgentIdGetData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/agents/{agent_id}';
};

export type GetAgentAgentsAgentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAgentAgentsAgentIdGetError = GetAgentAgentsAgentIdGetErrors[keyof GetAgentAgentsAgentIdGetErrors];

export type GetAgentAgentsAgentIdGetResponses = {
    /**
     * Successful Response
     */
    200: Agent;
};

export type GetAgentAgentsAgentIdGetResponse = GetAgentAgentsAgentIdGetResponses[keyof GetAgentAgentsAgentIdGetResponses];

export type UpdateAgentAgentsAgentIdPatchData = {
    body: AgentUpdate;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/agents/{agent_id}';
};

export type UpdateAgentAgentsAgentIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAgentAgentsAgentIdPatchError = UpdateAgentAgentsAgentIdPatchErrors[keyof UpdateAgentAgentsAgentIdPatchErrors];

export type UpdateAgentAgentsAgentIdPatchResponses = {
    /**
     * Successful Response
     */
    200: Agent;
};

export type UpdateAgentAgentsAgentIdPatchResponse = UpdateAgentAgentsAgentIdPatchResponses[keyof UpdateAgentAgentsAgentIdPatchResponses];

export type ListAgentToolsAgentsAgentIdToolsGetData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/agents/{agent_id}/tools';
};

export type ListAgentToolsAgentsAgentIdToolsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAgentToolsAgentsAgentIdToolsGetError = ListAgentToolsAgentsAgentIdToolsGetErrors[keyof ListAgentToolsAgentsAgentIdToolsGetErrors];

export type ListAgentToolsAgentsAgentIdToolsGetResponses = {
    /**
     * Response List Agent Tools Agents  Agent Id  Tools Get
     *
     * Successful Response
     */
    200: Array<Tool>;
};

export type ListAgentToolsAgentsAgentIdToolsGetResponse = ListAgentToolsAgentsAgentIdToolsGetResponses[keyof ListAgentToolsAgentsAgentIdToolsGetResponses];

export type DetachToolAgentsAgentIdToolsToolIdDeleteData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
        /**
         * Tool Id
         */
        tool_id: string;
    };
    query?: never;
    url: '/agents/{agent_id}/tools/{tool_id}';
};

export type DetachToolAgentsAgentIdToolsToolIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DetachToolAgentsAgentIdToolsToolIdDeleteError = DetachToolAgentsAgentIdToolsToolIdDeleteErrors[keyof DetachToolAgentsAgentIdToolsToolIdDeleteErrors];

export type DetachToolAgentsAgentIdToolsToolIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AttachToolAgentsAgentIdToolsToolIdPostData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
        /**
         * Tool Id
         */
        tool_id: string;
    };
    query?: never;
    url: '/agents/{agent_id}/tools/{tool_id}';
};

export type AttachToolAgentsAgentIdToolsToolIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AttachToolAgentsAgentIdToolsToolIdPostError = AttachToolAgentsAgentIdToolsToolIdPostErrors[keyof AttachToolAgentsAgentIdToolsToolIdPostErrors];

export type AttachToolAgentsAgentIdToolsToolIdPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListChatsChatsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Agent Id
         */
        agent_id?: string | null;
    };
    url: '/chats';
};

export type ListChatsChatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListChatsChatsGetError = ListChatsChatsGetErrors[keyof ListChatsChatsGetErrors];

export type ListChatsChatsGetResponses = {
    /**
     * Response List Chats Chats Get
     *
     * Successful Response
     */
    200: Array<Chat>;
};

export type ListChatsChatsGetResponse = ListChatsChatsGetResponses[keyof ListChatsChatsGetResponses];

export type CreateChatChatsPostData = {
    body: ChatCreate;
    path?: never;
    query?: never;
    url: '/chats';
};

export type CreateChatChatsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateChatChatsPostError = CreateChatChatsPostErrors[keyof CreateChatChatsPostErrors];

export type CreateChatChatsPostResponses = {
    /**
     * Successful Response
     */
    200: Chat;
};

export type CreateChatChatsPostResponse = CreateChatChatsPostResponses[keyof CreateChatChatsPostResponses];

export type GetChatChatsChatIdGetData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/chats/{chat_id}';
};

export type GetChatChatsChatIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChatChatsChatIdGetError = GetChatChatsChatIdGetErrors[keyof GetChatChatsChatIdGetErrors];

export type GetChatChatsChatIdGetResponses = {
    /**
     * Successful Response
     */
    200: Chat;
};

export type GetChatChatsChatIdGetResponse = GetChatChatsChatIdGetResponses[keyof GetChatChatsChatIdGetResponses];

export type ListMessagesMessagesByChatChatIdGetData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/messages/by-chat/{chat_id}';
};

export type ListMessagesMessagesByChatChatIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMessagesMessagesByChatChatIdGetError = ListMessagesMessagesByChatChatIdGetErrors[keyof ListMessagesMessagesByChatChatIdGetErrors];

export type ListMessagesMessagesByChatChatIdGetResponses = {
    /**
     * Response List Messages Messages By Chat  Chat Id  Get
     *
     * Successful Response
     */
    200: Array<Message>;
};

export type ListMessagesMessagesByChatChatIdGetResponse = ListMessagesMessagesByChatChatIdGetResponses[keyof ListMessagesMessagesByChatChatIdGetResponses];

export type AddMessageMessagesPostData = {
    body: MessageCreate;
    path?: never;
    query?: never;
    url: '/messages';
};

export type AddMessageMessagesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddMessageMessagesPostError = AddMessageMessagesPostErrors[keyof AddMessageMessagesPostErrors];

export type AddMessageMessagesPostResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type AddMessageMessagesPostResponse = AddMessageMessagesPostResponses[keyof AddMessageMessagesPostResponses];
